services:
  main-database:
    image: postgres:13
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: 
      "postgres -c 'max_connections=500'"
      
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RAILS_MAX_THREADS=5
    ports:
      - "5432:5432"
  main-redis:
    image: redis:latest
    container_name: redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: >
      sh -c '
        mkdir -p /usr/local/etc/redis &&
        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
        echo "requirepass $REDIS_PASSWORD" >> /usr/local/etc/redis/redis.conf &&
        echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
        redis-server /usr/local/etc/redis/redis.conf
      '
    tty: true
    stdin_open: true

  sidekiq:
    build: .
    container_name: sidekiq
    command: bundle exec sidekiq -C config/sidekiq.yml 
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_URL=${REDIS_URL}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - SIDEKIQ_USERNAME=${SIDEKIQ_USERNAME}
      - SIDEKIQ_PASSWORD=${SIDEKIQ_PASSWORD}
    depends_on:
      - main-database
      - main-redis

  rails-app-1:
    build: .
    container_name: rails-api-1
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:create db:migrate && bundle exec rails server -b 0.0.0.0 -p 3000"
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@main-redis:6379/0
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - DEVELOPMENT_PRIMARY=${DEVELOPMENT_PRIMARY}
      - DEVELOPMENT_QUEUE=${DEVELOPMENT_QUEUE}
      - DEVELOPMENT_CACHE=${DEVELOPMENT_CACHE}
      - DEVELOPMENT_CABLE=${DEVELOPMENT_CABLE}
    volumes:
      - app-storage:/rails/storage
      - rails-pids-1:/rails/tmp/pids
      - .:/rails:cached
    depends_on:
      - main-database
      - main-redis
  
  rails-app-2:
    build: .
    container_name: rails-api-2
    command: bash -c "rm -f tmp/pids/server.pid  && bundle exec rails server -b 0.0.0.0 -p 3000"
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@main-redis:6379/0
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - DEVELOPMENT_PRIMARY=${DEVELOPMENT_PRIMARY}
      - DEVELOPMENT_QUEUE=${DEVELOPMENT_QUEUE}
      - DEVELOPMENT_CACHE=${DEVELOPMENT_CACHE}
      - DEVELOPMENT_CABLE=${DEVELOPMENT_CABLE}
    volumes:
      - app-storage:/rails/storage
      - rails-pids-2:/rails/tmp/pids
    depends_on:
      - main-database
      - main-redis
      - rails-app-1

  rails-app-3:
    build: .
    container_name: rails-api-3
    command: bash -c "rm -f tmp/pids/server.pid  && bundle exec rails server -b 0.0.0.0 -p 3000"
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_URL=redis://:${REDIS_PASSWORD}@main-redis:6379/0
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - DEVELOPMENT_PRIMARY=${DEVELOPMENT_PRIMARY}
      - DEVELOPMENT_QUEUE=${DEVELOPMENT_QUEUE}
      - DEVELOPMENT_CACHE=${DEVELOPMENT_CACHE}
      - DEVELOPMENT_CABLE=${DEVELOPMENT_CABLE}
    volumes:
      - app-storage:/rails/storage
      - rails-pids-3:/rails/tmp/pids
    depends_on:
      - main-database
      - main-redis
      - rails-app-1
  
  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - rails-app-1
      - rails-app-2
      - rails-app-3
    
volumes:
  postgres_data: {}
  app-storage: {}
  rails-pids-1: {}
  rails-pids-2: {}
  rails-pids-3: {}
