default: &default
  adapter: postgresql
  encoding: unicode
  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>
  port: <%= ENV['POSTGRES_PORT'] || 5432 %>



development:
  primary: &primary_development
    <<: *default
    database: <%= ENV['POSTGRES_DB'] %>
    username: <%= ENV['POSTGRES_USER'] %>
    password: <%= ENV['POSTGRES_PASSWORD'] %>
    host: <%= ENV['POSTGRES_HOST'] %>
  cache:
    <<: *primary_development
    database: <%= ENV['DEVELOPMENT_CACHE'] %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_development
    database: <%= ENV['DEVELOPMENT_QUEUE']  %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_development
    database: <%= ENV['DEVELOPMENT_CABLE']  %>
    migrations_paths: db/cable_migrate
  
test:
  <<: *default
  database: schedule_api_test
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>


production:
  primary: &primary_production
    <<: *default
    database: <%= ENV['POSTGRES_DB'] %>
    username: <%= ENV['POSTGRES_USER'] %>
    password: <%= ENV['POSTGRES_PASSWORD'] %>
  cache:
    <<: *primary_production
    database: schedule_api_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: schedule_api_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: schedule_api_production_cable
    migrations_paths: db/cable_migrate